baseurl = "/"
languageCode = "en-us"
theme = "hello"
paginate = 1000000

[languages]
  [languages.en]
    title = "./side_effects.sh"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = ""
    writtenBy = ""
    readMore = ""
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    googleAnalytics = "UA-77368278-1"
    [languages.en.params]
      # dir name of your blog content (default is `content/posts`)
      contentTypeName = "posts"
      # "light" or "dark"
      defaultTheme = "dark"
      # if you set this to 0, only submenu trigger will be visible
      showMenuItems = 4
      # Show reading time in minutes for posts
      showReadingTime = false

      [languages.en.params.logo]
        logoText = "./side_effects.sh"
        logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "cv"
        name = "CV"
        url = "/cv"
      [[languages.en.menu.main]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/zafirovalexander/"
      [[languages.en.menu.main]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/z4f1r0v"
